{{- if .Values.auth.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "argus.fullname" . }}-credentials
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.auth.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.externalSecrets.secretStoreName }}
    kind: {{ .Values.auth.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "argus.fullname" . }}-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.auth.externalSecrets.remoteDbKey | quote }}
        property: "password"
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.auth.externalSecrets.remoteAwsKey | quote }}
        property: "aws_access_key_id"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.auth.externalSecrets.remoteAwsKey | quote }}
        property: "aws_secret_access_key"
    - secretKey: ARGUS_AUTH_TOKEN
      remoteRef:
        key: {{ .Values.auth.externalSecrets.remoteDbKey | quote }}
        property: "argus_auth_token"
{{- end }}
